name: classifyme
description: Official ClassifyMe web app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  dio: ^4.0.4
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
  fonts:
    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: InterLight
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
